### PR TITLE
Pretty print test duration artifact

### PR DESCRIPTION
**Pull request by vpipkt**
This will enable cleaner comparisons for duration artifacts stored in VCS.

### CODE REVIEW

**Comment by jerry-git** [comment]
Sorry, seems that I haven't seen this before. Hmm, the CI (GHA) doesn't run for some reason 🤔

**Comment by vpipkt** [comment]
Any ideas what is going wrong with the CI build? It is failing installing poetry... 😞

**Comment by jerry-git** [comment]
I updated the install-poetry action, pull the latest changes from master please 🙂

**Review by jerry-git — APPROVED** [review]
Thanks for the contribution!

**Comment by jerry-git** [comment]
Available in 0.4.0

**Pull request merged**
